#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]

REQUIRED_FILES = [
    "README.md",
    "README.zh-CN.md",
    "SKILL.md",
    "LICENSE",
    "CHANGELOG.md",
    "docs/releases/README.md",
    "docs/releases/RELEASE_NOTES_v0.1.0.md",
    "docs/releases/RELEASE_NOTES_v0.1.1.md",
    "docs/releases/RELEASE_NOTES_v0.1.2.md",
    "docs/releases/RELEASE_NOTES_v0.1.3.md",
    "docs/releases/RELEASE_NOTES_v0.1.4.md",
    "docs/releases/RELEASE_NOTES_v0.1.5.md",
    "docs/releases/RELEASE_NOTES_v0.2.0.md",
    "docs/releases/RELEASE_NOTES_v0.2.1.md",
    "docs/releases/RELEASE_NOTES_v0.2.2.md",
    "docs/releases/RELEASE_NOTES_v0.2.3.md",
    "docs/releases/RELEASE_NOTES_v0.2.4.md",
    "docs/releases/RELEASE_NOTES_v3.0.md",
    "docs/releases/RELEASE_NOTES_v3.0.1.md",
    "docs/analystm_replacement_coverage.md",
    "pyproject.toml",
    "src/analystm/__init__.py",
    "src/analystm/__main__.py",
    "src/analystm/approval.py",
    "src/analystm/atom_ai.py",
    "src/analystm/bias_utils.py",
    "src/analystm/bragg_phase.py",
    "src/analystm/dataset_utils.py",
    "src/analystm/domain_wall.py",
    "src/analystm/export.py",
    "src/analystm/fft_filter.py",
    "src/analystm/fft_windowing.py",
    "src/analystm/deconvolution.py",
    "src/analystm/gap_map.py",
    "src/analystm/gap_fitting.py",
    "src/analystm/gap_models.py",
    "src/analystm/gap_priority.py",
    "src/analystm/histogram.py",
    "src/analystm/import_io.py",
    "src/analystm/intensity.py",
    "src/analystm/io.py",
    "src/analystm/models.py",
    "src/analystm/map_crop.py",
    "src/analystm/multipeak.py",
    "src/analystm/nanonis_io.py",
    "src/analystm/numerics.py",
    "src/analystm/phase_lockin.py",
    "src/analystm/path_viz.py",
    "src/analystm/publication.py",
    "src/analystm/qpi.py",
    "src/analystm/sjtm.py",
    "src/analystm/spectroscopy.py",
    "src/analystm/spstm.py",
    "src/analystm/topography.py",
    "src/analystm/topography_display.py",
    "src/analystm/waterfall.py",
    "src/analystm/cli/main.py",
    "pysidam_agent_core/__init__.py",
    "pysidam_agent_core/approval.py",
    "pysidam_agent_core/gap_priority.py",
    "pysidam_agent_core/io.py",
    "pysidam_agent_core/models.py",
    "pysidam_agent_core/numerics.py",
    "pysidam_agent_core/gap_fitting.py",
    "pysidam_agent_core/bragg_phase.py",
    "pysidam_agent_core/phase_lockin.py",
    "pysidam_agent_core/atom_ai.py",
    "pysidam_agent_core/domain_wall.py",
    "scripts/approval_gate.py",
    "scripts/probe_runtime.py",
    "scripts/resolve_runtime.py",
    "scripts/bootstrap_runtime.py",
    "scripts/sync_installed_skill.py",
    "scripts/pysidam_agent/__init__.py",
    "scripts/pysidam_agent/common.py",
    "scripts/pysidam_agent/capabilities.py",
    "scripts/pysidam_agent/read_file.py",
    "scripts/pysidam_agent/plot_spectrum.py",
    "scripts/pysidam_agent/fit_gap.py",
    "scripts/pysidam_agent/bragg_phase.py",
    "scripts/pysidam_agent/phase_lockin.py",
    "scripts/pysidam_agent/atom_ai.py",
    "scripts/pysidam_agent/domain_wall.py",
    "runtime/constraints.txt",
    "runtime/requirements-core.txt",
    "runtime/requirements-nanonis.txt",
    "runtime/requirements-ibw.txt",
    "runtime/requirements-ai.txt",
    "references/workflow.md",
    "references/runtime-bootstrap.md",
    "references/format-io-matrix.md",
    "references/data-contracts.md",
    "references/nanonis-3ds-ingest.md",
    "references/fitting-recipes.md",
    "references/pysidam-tool-map.md",
    "references/pysidam-capability-map.md",
    "references/pysidam-capability-index.json",
    "references/approval-gates.md",
    "references/task-cards/sts-dat-quick.md",
    "references/task-cards/gap-fit-quick.md",
    "references/quality-checks.md",
    "references/reporting.md",
    "assets/approval-gate-template.html",
    "tests/test_approval_gate.py",
    "tests/test_atom_ai_core.py",
    "tests/test_domain_wall_core.py",
    "tests/test_domain_wall_cli.py",
    "tests/test_analystm_export.py",
    "tests/test_analystm_display_surfaces.py",
    "tests/test_phase_lockin_core.py",
    "tests/test_phase_lockin_cli.py",
    "tests/test_analystm_path_viz.py",
    "tests/test_analystm_publication.py",
    "tests/test_analystm_grid_deconvolution.py",
    "tests/test_analystm_histogram_crop.py",
    "tests/test_analystm_intensity.py",
    "tests/test_analystm_multipeak.py",
    "tests/test_analystm_qpi.py",
    "tests/test_analystm_qpi1d_filter.py",
    "tests/test_analystm_topography.py",
    "tests/test_analystm_waterfall.py",
    "tests/test_analystm_public_backend.py",
    "tests/test_analystm_replacement_backend.py",
    "tests/test_analystm_real_surfaces.py",
    "tests/test_analystm_sjtm.py",
    "tests/test_analystm_spstm.py",
    "tests/test_runtime_defaults.py",
]

REQUIRED_TOKENS = {
    "README.md": [
        "STM/SJTM Data Processing Agent Skill",
        "Quick Start",
        "Skill Installation",
        "Other Agent Runtimes",
        "GitHub Release",
        "scripts/probe_runtime.py",
        "scripts/resolve_runtime.py",
        "scripts/bootstrap_runtime.py",
        "scripts/sync_installed_skill.py",
        "scripts/pysidam_agent/read_file.py",
        "scripts/pysidam_agent/fit_gap.py",
        "scripts/pysidam_agent/bragg_phase.py",
        "scripts/pysidam_agent/phase_lockin.py",
        "scripts/pysidam_agent/atom_ai.py",
        "scripts/pysidam_agent/domain_wall.py",
        "references/task-cards/sts-dat-quick.md",
        "references/task-cards/gap-fit-quick.md",
        "references/pysidam-capability-index.json",
        "runtime/requirements-core.txt",
    ],
    "README.zh-CN.md": [
        "STM/SJTM 数据处理 Agent Skill",
        "README.md",
        "README.zh-CN.md",
        "快速开始",
        "Skill 安装",
        "Other Agent Runtimes",
        "GitHub Release",
        "AnalySTM Backend",
        "public installable",
        "analystm read",
        "analystm plot-spectrum",
        "analystm spectroscopy",
        "analystm fit-gap",
        "analystm bragg",
        "analystm phase-lockin",
        "analystm gap-map",
        "analystm intensity",
        "analystm waterfall",
        "analystm qpi",
        "analystm qpi 1d-fft",
        "analystm qpi fft-filter",
        "analystm topography",
        "analystm topography display-fft",
        "analystm topography fft-filter",
        "analystm histogram",
        "analystm crop",
        "analystm path-viz",
        "analystm publication",
        "analystm export",
        "analystm sjtm",
        "analystm deconvolve",
        "analystm atom",
        "analystm domain-wall",
        "scripts/probe_runtime.py",
        "scripts/resolve_runtime.py",
        "scripts/bootstrap_runtime.py",
        "scripts/sync_installed_skill.py",
        "scripts/pysidam_agent/read_file.py",
        "scripts/pysidam_agent/fit_gap.py",
        "scripts/pysidam_agent/bragg_phase.py",
        "scripts/pysidam_agent/phase_lockin.py",
        "scripts/pysidam_agent/atom_ai.py",
        "scripts/pysidam_agent/domain_wall.py",
        "references/task-cards/sts-dat-quick.md",
        "references/task-cards/gap-fit-quick.md",
        "references/pysidam-capability-index.json",
        "runtime/requirements-core.txt",
    ],
    "SKILL.md": [
        "name: stm-sjtm-data-processing",
        "AnalySTM",
        "quick card",
        "Ask the user to choose a fitting mode",
        "analystm read",
        "analystm plot-spectrum",
        "analystm spectroscopy",
        "analystm fit-gap",
        "analystm bragg",
        "analystm phase-lockin",
        "analystm intensity",
        "analystm waterfall",
        "analystm qpi",
        "analystm qpi 1d-fft",
        "analystm qpi fft-filter",
        "analystm topography",
        "analystm topography display-fft",
        "analystm histogram",
        "analystm crop",
        "analystm path-viz",
        "analystm publication",
        "analystm export",
        "analystm atom",
        "analystm domain-wall",
        "Reportable analysis MUST use the AnalySTM public backend",
        "Do not write task-local replacements for AnalySTM commands or APIs",
        "Every reportable output must name an AnalySTM execution engine",
        "scripts/resolve_runtime.py --probe",
        "Legacy PySIDAM source mapping",
        "references/pysidam-capability-index.json",
        "Fast Tool Routing",
        "scripts/pysidam_agent/capabilities.py --query",
        "references/approval-gates.md",
        "approval gate",
        "fit_window",
        "q_selection",
        "peak_count",
        "references/runtime-bootstrap.md",
        "references/data-contracts.md",
        "references/quality-checks.md",
        "references/format-io-matrix.md",
        "references/nanonis-3ds-ingest.md",
        "Do not make phase conclusions from real-IFFT images alone.",
        "lockin_engine = analystm.phase_lockin.lockin_phase_extraction",
        "resize_ratio",
        "lattice-qc",
        "wipe-regions",
        "domain_wall.py",
    ],
    "references/runtime-bootstrap.md": [
        "nanonispy",
        "Atom_Identificator_core",
        "igorwriter",
        "bootstrap_runtime.py",
        "resolve_runtime.py",
        "runtime.json",
        "host.json",
        "user-writable",
        "no sudo",
        "git fetch origin --prune",
        "do not merge or reset",
    ],
    "references/nanonis-3ds-ingest.md": [
        "read_nanonis_file",
        "prepare_3ds_dataset",
        "(x, y, bias)",
        "divider=1.0",
        "Do not hand-roll",
    ],
    "references/format-io-matrix.md": [
        ".3ds",
        ".sxm",
        ".dat",
        ".ibw",
        ".npz",
        "PXP is not",
        "normalize_sxm_direction_map",
        "imported_file_to_numeric_table",
        "analystm export",
    ],
    "references/workflow.md": [
        "Ingest",
        "runtime bootstrap",
        "Normalize Data Contracts",
        "Topography Processing",
        "atom_ai.py recommend-scale",
        "Spectroscopy Processing",
        "SJTM-Specific Maps",
        "Fourier, QPI, And Lock-In",
        "phase_lockin.py run",
        "Cross-Observable Analysis",
        "Evidence Package",
    ],
    "references/data-contracts.md": [
        "(y, x)",
        "(y, x, bias)",
        "(bias, y, x)",
        "(x, y, bias)",
        "bias unit",
        "coordinate frame",
    ],
    "references/fitting-recipes.md": [
        "Superconducting Gap Fitting",
        "Dynes",
        "SIS",
        "NIS",
        "Multipeak",
        "approval gate",
        "fit_window",
        "peak_count",
        "strict-pysidam-compatible",
        "gap-priority experimental",
        "Peak Height, Z-Ratio, And Bias Calibration",
        "analystm intensity",
    ],
    "references/pysidam-tool-map.md": [
        "origin/main",
        "pysidam.core.nanonis_io",
        "pysidam.core.dataset_utils",
        "pysidam_agent",
        "references/pysidam-capability-index.json",
        "Do not instantiate Qt",
        "LFDriftCorrector",
        "analystm topography display-fft",
        "PeakFitter.fit_single_pixel",
        "UniversalVortexFitterEngine",
        "analystm waterfall",
        "fit_nis_dynes_didv",
        "write_nanonis_grid_3ds",
        "lockin_phase_extraction",
        "analystm qpi",
        "phase_lockin.py run",
        "SJTMIcExtractionWindow",
        "SJTMSuperfluidDensityWindow",
        "qpi_1D_QPI",
        "topography_filter.FFTFilterWindow",
        "analystm histogram",
        "analystm crop map",
        "analystm path-viz",
        "analystm publication",
    ],
    "references/pysidam-capability-map.md": [
        "PySIDAM Capability Map",
        "HEADLESS_READY",
        "GUI_WRAPPED_EXTRACT",
        "OPTIONAL_DEP",
        "pysidam_agent",
        "phase_lockin.py",
        "atom_ai.py",
        "domain_wall.py",
        "capability index",
    ],
    "pysidam_agent_core/bragg_phase.py": [
        "q_selection_policy",
        "find_peak_in_roi",
        "preprocess_topography",
    ],
    "pysidam_agent_core/phase_lockin.py": [
        "LOCKIN_ENGINE",
        "q_cycles_to_pysidam_px_yx",
        "run_pysidam_lockin",
        "pysidam.qpi_analysis.qpi_phase_analysis.lockin_phase_extraction",
    ],
    "pysidam_agent_core/atom_ai.py": [
        "scale_recommendation",
        "lattice_qc",
        "apply_wipe_regions",
        "resize_ratio",
        "fourfold_order",
    ],
    "pysidam_agent_core/domain_wall.py": [
        "domain_wall_policy",
        "build_domain_wall_masks",
        "region_stats",
        "broad_dw_mask",
        "away_mask",
    ],
    "scripts/pysidam_agent/bragg_phase.py": [
        "policy",
        "inspect-roi",
        "lockin-from-decision",
    ],
    "scripts/pysidam_agent/phase_lockin.py": [
        "parse_q_args",
        "write_outputs",
        "run_pysidam_lockin",
        "phase_lockin_maps.npz",
    ],
    "scripts/pysidam_agent/atom_ai.py": [
        "recommend-scale",
        "lattice-qc",
        "wipe-regions",
        "pysidam_agent_core.atom_ai",
    ],
    "scripts/pysidam_agent/domain_wall.py": [
        "policy",
        "build-masks",
        "stats",
        "domain_wall_masks.npz",
        "pysidam_agent_core.domain_wall",
    ],
    "references/pysidam-capability-index.json": [
        "\"schema_version\"",
        "\"pysidam_commit\"",
        "\"HEADLESS_READY\"",
        "\"GUI_WRAPPED_EXTRACT\"",
        "\"core_io\"",
        "\"spectroscopy_display\"",
        "\"agent_atom_ai_scale_qc_wipe\"",
        "\"clean_2d_phase_lockin_bridge\"",
        "\"domain_wall_mask_stats_bridge\"",
        "\"qpi_lockin\"",
        "\"one_dimensional_qpi\"",
        "\"qpi_fft_filter\"",
        "\"topography_fft_filter\"",
        "\"waterfall_and_grid_views\"",
        "\"useful_histogram\"",
        "\"useful_map_crop\"",
        "\"surface_survey_path_viz\"",
        "\"publication_editor\"",
        "\"sjtm\"",
        "\"deconvolution\"",
    ],
    "references/task-cards/sts-dat-quick.md": [
        "STS DAT Quick Card",
        "resolve_runtime.py --probe",
        "pysidam_agent/read_file.py",
        "pysidam_agent/plot_spectrum.py",
        "no scientific conclusion",
    ],
    "references/task-cards/gap-fit-quick.md": [
        "Gap Fit Quick Card",
        "pysidam_agent/fit_gap.py",
        "pysidam_agent_core.gap_fitting.fit_gap_model_guarded",
        "two_band_splusminus_gap_priority",
        "fit_overlay_overview.png",
        "quantitative fitting must produce diagnostic plots",
        "Ask before fitting",
        "strict-pysidam-compatible",
        "gap-priority experimental",
        "Do not write a new optimizer",
        "PySIDAM UI fitter import is blocked",
    ],
    "references/quality-checks.md": [
        "Data-Contract Gates",
        "Fitting Gates",
        "FFT And Lock-In Gates",
        "lockin_phase_extraction",
        "AI Atom Detection Gates",
        "Cross-Observable Gates",
        "Reporting Gates",
        "approval gate",
        "fit_window",
        "q_selection",
        "peak_count",
    ],
    "references/reporting.md": [
        "report.json",
        "approval gate",
        "fit_window",
        "q_selection",
        "peak_count",
        "inputs",
        "data_contract",
        "quality",
        "warnings",
        "software",
    ],
    "CHANGELOG.md": ["v3.0.1", "AnalySTM runtime independent of PySIDAM", "Initial preview release"],
    "docs/releases/README.md": ["Release Notes", "GitHub Releases", "RELEASE_NOTES_v3.0.1.md"],
    "docs/releases/RELEASE_NOTES_v0.1.0.md": ["v0.1.0", "Release checklist"],
    "docs/releases/RELEASE_NOTES_v0.1.1.md": ["v0.1.1", "runtime bootstrap", "probe_runtime.py"],
    "docs/releases/RELEASE_NOTES_v0.1.2.md": ["v0.1.2", "bootstrap_runtime.py", "isolated"],
    "docs/releases/RELEASE_NOTES_v0.1.3.md": ["v0.1.3", "resolve_runtime.py", "host.json"],
    "docs/releases/RELEASE_NOTES_v0.1.4.md": ["v0.1.4", "quick card", "pysidam_agent", "sync_installed_skill.py"],
    "docs/releases/RELEASE_NOTES_v0.1.5.md": ["v0.1.5", "fit_gap.py", "fit_selected_gap_dos_model_guarded", "Do not write a new optimizer"],
    "docs/releases/RELEASE_NOTES_v0.2.0.md": ["v0.2.0", "pysidam_agent_core", "headless", "fit_gap_model_guarded"],
    "docs/releases/RELEASE_NOTES_v0.2.1.md": ["v0.2.1", "strict-pysidam-compatible", "gap-priority experimental", "Ask before fitting"],
    "docs/releases/RELEASE_NOTES_v0.2.2.md": ["v0.2.2", "two_band_splusminus_gap_priority", "--save-overview", "fit_overlay_overview.png"],
    "docs/releases/RELEASE_NOTES_v0.2.3.md": ["v0.2.3", "approval gate", "fit_window", "q_selection", "peak_count"],
    "docs/releases/RELEASE_NOTES_v0.2.4.md": [
        "v0.2.4",
        "bragg_phase.py",
        "divider",
        "read_file.py --quick",
        "user-specified q",
    ],
    "docs/releases/RELEASE_NOTES_v3.0.md": [
        "v3.0",
        "AnalySTM",
        "analystm",
        "public installable",
        "private PySIDAM",
        "gap-map",
        "multipeak",
        "intensity",
        "export",
        "QPI",
        "1D-QPI",
        "FFT ROI",
        "topography LF drift",
        "deconvolution",
        "SPSTM",
    ],
    "docs/releases/RELEASE_NOTES_v3.0.1.md": [
        "v3.0.1",
        "AnalySTM",
        "PySIDAM",
        "UI packages",
        "planned external integration",
        "probe_runtime.py",
        "bootstrap_runtime.py",
        "resolve_runtime.py",
        "runtime/requirements-ui.txt",
        "tests/test_runtime_defaults.py",
    ],
    "pyproject.toml": [
        'name = "analystm"',
        'version = "3.0.1"',
        "[project.scripts]",
        'analystm = "analystm.cli.main:main"',
    ],
    "src/analystm/__init__.py": [
        "__version__",
        "fit_gap_model_guarded",
        "scale_recommendation",
        "run_lockin_phase",
        "run_pysidam_lockin",
        "build_domain_wall_masks",
        "write_nanonis_spec_dat",
        "build_linear_resample_matrix",
        "build_pinv_operator",
        "process_intensity_matrix",
        "compute_z_ratio_map",
        "symmetrize_qpi",
        "compute_pr_qpi_volume",
        "compute_fft_base_volume",
        "compute_qpi_1d_fft",
        "compute_real_phase_pll",
        "run_fft_filter",
        "build_qpi_r90_contrast",
        "process_didv_contrast",
        "LFDriftCorrector",
        "estimate_lf_displacement_from_q_vectors",
        "UniversalVortexFitterEngine",
        "run_multipeak_fit",
    ],
    "src/analystm/__main__.py": ["from .cli.main import main"],
    "src/analystm/cli/main.py": [
        "AnalySTM headless STM/SJTM analysis backend",
        "read",
        "plot-spectrum",
        "fit-gap",
        "gap-map",
        "multipeak",
        "bragg",
        "phase-lockin",
        "atom",
        "domain-wall",
        "sjtm",
        "deconvolve",
        "export",
        "intensity",
        "qpi",
        "spstm",
        "topography",
        "fft-volume",
        "1d-fft",
        "fft-filter",
        "real-phase",
        "cmd_multipeak",
        "cmd_gap_map",
        "cmd_intensity",
        "cmd_qpi",
        "cmd_spstm",
        "cmd_topography",
        "cmd_sjtm",
        "cmd_deconvolve",
    ],
    "src/analystm/phase_lockin.py": [
        "LOCKIN_ENGINE",
        "analystm.phase_lockin.lockin_phase_extraction",
        "lockin_phase_extraction",
        "q_cycles_to_pysidam_px_yx",
        "run_lockin_phase",
        "run_pysidam_lockin = run_lockin_phase",
    ],
    "src/analystm/gap_map.py": [
        "fit_single_peak",
        "extract_gap_map",
        "PeakFitter.fit_single_pixel",
        "analystm.gap_map.extract_gap_map",
        "pysidam_source_mapping",
        "gap=(right_peak-left_peak)/2",
    ],
    "src/analystm/export.py": [
        "write_nanonis_spec_dat",
        "write_nanonis_grid_3ds",
        "write_ibw_wave",
        "core.export.write_nanonis_spec_dat",
        "pysidam_source_mapping",
    ],
    "src/analystm/sjtm.py": [
        "compute_ic_map",
        "compute_superfluid_metrics",
        "compute_sjtm_package",
        "analystm.sjtm.compute_sjtm_package",
        "SJTMIcExtractionWindow._compute_ic_map",
        "SJTMSuperfluidDensityWindow._compute_metrics",
        "fit_mode",
        "Accurate",
        "pysidam_source_mapping",
    ],
    "src/analystm/intensity.py": [
        "apply_intensity_signal_mode",
        "process_intensity_matrix",
        "peak_align_zero_cube",
        "compute_z_ratio_map",
        "extract_h_cut",
        "extract_v_cut",
        "linecutmap_intensity",
        "qpi_pr_pqi",
        "analystm.intensity.process_intensity_matrix",
        "analystm.intensity.peak_align_zero_cube",
        "analystm.intensity.compute_z_ratio_map",
        "pysidam_source_mapping",
    ],
    "src/analystm/qpi.py": [
        "symmetrize_qpi",
        "run_qpi_symmetry",
        "compute_pr_qpi_volume",
        "compute_fft_base_volume",
        "compute_qpi_1d_fft",
        "build_fft_q0_gaussian_notch_1d_discrete",
        "run_qpi_fft",
        "real_phase_lockin",
        "compute_real_phase_pll",
        "qpi_1D_QPI",
        "qpi_symmetry.symmetrize_qpi",
        "qpi_pr_pqi._compute_pr_qpi_volume",
        "qpi_display._compute_fft_base_volume",
        "qpi_real_phase.lockin_phase",
        "analystm.qpi.symmetrize_qpi",
        "analystm.qpi.compute_pr_qpi_volume",
        "analystm.qpi.compute_fft_base_volume",
        "analystm.qpi.compute_real_phase_pll",
        "pysidam_source_mapping",
    ],
    "src/analystm/fft_filter.py": [
        "run_fft_filter",
        "build_fft_roi_mask",
        "prepare_fft_filter_input",
        "topography_filter.FFTFilterWindow.update_filtered",
        "qpi_filter.QPIFilterWindow._build_mask_2d",
        "pysidam_source_mapping",
    ],
    "src/analystm/topography.py": [
        "LFDriftCorrector",
        "compute_lf_drift_field_from_phases",
        "estimate_lf_displacement_from_q_vectors",
        "estimate_lf_displacement",
        "apply_lf_displacement_to_stack",
        "lf_q_vector_from_fft_pixel",
        "topography_correction.LFDriftCorrector",
        "qpi_symmetry.estimate_lf_displacement_from_q_vectors",
        "analystm.topography.estimate_lf_displacement_from_q_vectors",
        "pysidam_source_mapping",
    ],
    "src/analystm/multipeak.py": [
        "PeakFitResult",
        "UniversalVortexFitterEngine",
        "run_multipeak_fit",
        "collect_debug_state_payload",
        "BACKGROUND_FULL_TRACE_LINEAR",
        "BACKGROUND_IGOR_CUBIC",
        "LORENTZIAN_PROFILE",
        "analystm.multipeak.run_multipeak_fit",
        "pysidam_source_mapping",
    ],
    "src/analystm/spstm.py": [
        "process_didv_contrast",
        "auto_detect_offset",
        "sample_linecut",
        "normalize_profile",
        "build_qpi_r90_contrast",
        "build_qpi_spin_contrast",
        "SPSTMDidVContrastWindow.run_pipeline",
        "SPSTMQPIContrastWindow._build_result",
        "pysidam_source_mapping",
    ],
    "src/analystm/deconvolution.py": [
        "fit_nis_dynes_didv",
        "fit_sis_dynes_didv",
        "build_sis_didv_matrix",
        "solve_sis_sample_dos",
        "build_linear_resample_matrix",
        "build_pinv_operator",
        "compute_r2_score",
        "nanmean_cube_over_pixels",
        "run_sis_didv_deconvolution",
        "run_grid_deconvolution",
        "AnalySTM SIS dI/dV deconvolution",
        "analystm.deconvolution.run_sis_didv_deconvolution",
        "pysidam_source_mapping",
    ],
    "tests/test_analystm_public_backend.py": [
        "test_import_analystm_without_private_pysidam_root",
        "test_cli_help_lists_public_agent_commands",
        "test_public_backend_source_has_no_private_runtime_or_gui_dependency",
        "analystm atom lattice-qc",
        "analystm domain-wall build-masks",
        "export",
    ],
    "tests/test_analystm_export.py": [
        "test_spec_dat_writer_matches_pysidam_header_and_value_format",
        "test_grid_3ds_writer_header_and_payload_size_match_contract",
        "test_export_cli_writes_spec_dat_and_grid_3ds",
        "spec-dat",
        "grid-3ds",
    ],
    "tests/test_analystm_real_surfaces.py": [
        "test_gap_map_cli_runs_pysidam_peakfitter_algorithm",
        "test_sjtm_cli_runs_ic_and_superfluid_algorithms",
        "test_deconvolve_cli_runs_real_sis_deconvolution_not_proxy",
        "pysidam_source_mapping",
        "run_sis_didv_deconvolution",
    ],
    "tests/test_analystm_replacement_backend.py": [
        "test_sis_forward_model_uses_direct_integral_not_inverse_matrix_shortcut",
        "test_dos_display_normalization_uses_robust_tail_window",
        "test_deconvolution_reports_analystm_as_engine_and_pysidam_as_source_mapping",
        "analystm.deconvolution.run_sis_didv_deconvolution",
    ],
    "tests/test_analystm_grid_deconvolution.py": [
        "test_linear_resample_matrix_handles_interpolation_and_extrapolation",
        "test_build_pinv_operator_returns_weighted_operator_and_metadata",
        "test_grid_helpers_are_exported_from_analystm_namespace",
    ],
    "tests/test_analystm_intensity.py": [
        "test_signal_modes_match_pysidam_gradient_logic",
        "test_peak_align_zero_cube_migrates_bias_calibration",
        "test_z_ratio_uses_pysidam_negative_over_positive_regularization",
        "test_intensity_cli_process_z_ratio_and_peak_align",
    ],
    "tests/test_analystm_qpi.py": [
        "test_symmetrize_qpi_matches_rotate_average_contract",
        "test_pr_qpi_volume_matches_single_and_multi_impurity_branches",
        "test_fft_volume_matches_pysidam_display_contract",
        "test_real_phase_pll_matches_pysidam_wrapped_phase_formula",
        "test_qpi_cli_writes_symmetry_and_pr_qpi_reports",
        "test_qpi_cli_writes_fft_and_real_phase_reports",
    ],
    "tests/test_analystm_qpi1d_filter.py": [
        "test_qpi1d_fft_matches_pysidam_linecut_contract",
        "test_fft_filter_roi_mask_and_ifft_match_pysidam_contract",
        "test_cli_writes_qpi1d_and_fft_filter_reports",
        "analystm qpi 1d-fft",
        "analystm topography fft-filter",
    ],
    "tests/test_analystm_sjtm.py": [
        "test_ic_map_exposes_pysidam_quick_and_accurate_configs",
        "test_superfluid_g0_window_does_not_silently_expand_by_default",
        "test_sjtm_cli_accepts_accurate_ic_mode",
        "ic-fit-mode",
    ],
    "tests/test_analystm_spstm.py": [
        "test_didv_contrast_pipeline_symmetry_and_max_normalization",
        "test_qpi_r90_and_spin_contrast_match_pysidam_formulae",
        "test_spstm_cli_writes_didv_and_qpi_reports",
        "analystm spstm didv",
    ],
    "tests/test_analystm_topography.py": [
        "test_lf_corrector_peak_refinement_and_q_vector_match_pysidam",
        "test_drift_field_formula_uses_pysidam_sign_convention",
        "test_apply_lf_displacement_to_stack_identity_preserves_data",
        "test_topography_cli_lf_drift_writes_report_and_outputs",
    ],
    "tests/test_analystm_multipeak.py": [
        "test_run_multipeak_fit_matches_pysidam_engine_contract",
        "test_universal_vortex_fitter_engine_remains_public",
        "test_multipeak_cli_writes_outputs_and_report",
        "UniversalVortexFitterEngine.run_fit",
        "analystm multipeak fit",
    ],
    "docs/analystm_replacement_coverage.md": [
        "AnalySTM is the public replacement backend",
        "Coverage Matrix",
        "Core Nanonis export",
        "Grid deconvolution helpers",
        "Intensity / Z-ratio / bias calibration maps",
        "QPI display FFT",
        "1D-QPI",
        "FFT filter",
        "PR-QPI/PQPI",
        "real phase",
        "Topography LF drift correction",
        "Multipeak fitting",
        "SPSTM contrast",
    ],
    "pysidam_agent_core/__init__.py": [
        "fit_gap_model_guarded",
        "scale_recommendation",
        "run_pysidam_lockin",
        "build_domain_wall_masks",
    ],
    "pysidam_agent_core/approval.py": [
        "GATE_TYPES",
        "fit_window",
        "q_selection",
        "peak_count",
        "validate_proposal",
        "validate_decision",
        "validate_report_links_decision",
        "render_review_html",
    ],
    "pysidam_agent_core/gap_priority.py": [
        "PROFILE_TWO_BAND_SPLUSMINUS_GAP_PRIORITY",
        "fit_two_band_splusminus_gap_priority",
        "fit_gap_priority_modes",
        "candidate_fit_abs_mV",
        "center_platform_rmse_pA",
        "coherence_peak_rmse_pA",
        "boundary_hit",
    ],
    "pysidam_agent_core/io.py": ["load_signals", "read_nanonis_file", "read_imported_file"],
    "pysidam_agent_core/models.py": [
        "pysidam.core.superconducting_gap_models",
        "evaluate_gap_dos_model",
        "get_deconvolution_fit_param_spec",
    ],
    "pysidam_agent_core/numerics.py": [
        "normalize_xy_arrays",
        "feature_weights",
        "detect_gap_peak_positions",
        "solve_affine_reference_scale_offset",
    ],
    "pysidam_agent_core/gap_fitting.py": [
        "fit_gap_model_guarded",
        "fit_gap_model",
        "least_squares",
        "fit_feature_weighted",
    ],
    "scripts/probe_runtime.py": ["MODULES", "nanonispy", "Atom_Identificator_core", "git_info"],
    "scripts/resolve_runtime.py": [
        "HOST_CONFIG",
        "runtime.json",
        "--probe",
        "--print-python",
        "--bootstrap-command",
        "subprocess.check_call",
    ],
    "scripts/bootstrap_runtime.py": [
        "DEFAULT_GROUPS",
        "HOST_CONFIG",
        "load_host_config",
        "safe_venv_path",
        "--dry-run",
        "--no-network",
        "--pysidam-mode",
        "subprocess.check_call",
        "runtime.json",
    ],
    "scripts/sync_installed_skill.py": [
        "remove_installed_git",
        "stm-sjtm-data-processing",
        ".codex/skills",
        "dry-run",
    ],
    "scripts/pysidam_agent/common.py": [
        "ensure_runtime",
        "STM_SJTM_AGENT_RUNTIME_REEXEC",
        "runtime.json",
        "pysidam_root",
    ],
    "scripts/pysidam_agent/capabilities.py": [
        "pysidam-capability-index.json",
        "--domain",
        "--status",
        "--query",
        "matches_query",
        "Keyword search",
    ],
    "scripts/pysidam_agent/read_file.py": [
        "read_nanonis_file",
        "read_imported_file",
        "privacy",
        "signals_summary",
    ],
    "scripts/pysidam_agent/plot_spectrum.py": [
        "matplotlib.use(\"Agg\")",
        "Bias calc (V)",
        "LI Demod 1 X",
        "summary-json",
    ],
    "scripts/pysidam_agent/fit_gap.py": [
        "pysidam_agent_core.gap_fitting",
        "fit_gap_model_guarded",
        "two_band_splusminus_gap_priority",
        "--profile",
        "--symmetry",
        "--auto-fit-window",
        "--save-overview",
        "report.json",
        "pysidam_agent_core_import_failed",
        "Do not write a task-local optimizer",
        "fit_strategy",
        "fit_max_starts",
        "initial_params",
        "summary-json",
    ],
    "scripts/approval_gate.py": [
        "validate-proposal",
        "validate-decision",
        "validate-report",
        "render-html",
        "approval_proposal.json",
        "approval_decision.json",
    ],
    "tests/test_atom_ai_core.py": [
        "test_resize_1p5_matches_fts_spin_pixel_scale",
        "test_square_lattice_qc_passes_orderly_grid",
        "test_apply_wipe_regions_marks_dw_band_and_dirty_spot",
    ],
    "tests/test_domain_wall_core.py": [
        "test_policy_asks_before_agent_dw_search_without_user_regions",
        "test_build_masks_from_user_x_band_with_near_and_away_regions",
        "test_refined_on_dw_keeps_broad_strip_out_of_away_region",
    ],
    "tests/test_domain_wall_cli.py": [
        "test_load_numeric_map_reads_npy_and_npz",
        "test_write_mask_outputs_saves_npz_and_report",
    ],
    "tests/test_phase_lockin_core.py": [
        "test_q_cycles_convert_to_pysidam_absolute_pixels",
        "test_run_pysidam_lockin_emits_standard_maps_and_engine",
    ],
    "tests/test_phase_lockin_cli.py": [
        "test_parse_q_args_accepts_labels_and_auto_labels",
        "test_write_outputs_saves_report_npz_and_stats",
    ],
    "references/approval-gates.md": [
        "Approval Gates",
        "fit_window",
        "q_selection",
        "peak_count",
        "user_preapproved",
        "approval_proposal.json",
        "approval_decision.json",
    ],
    "assets/approval-gate-template.html": [
        "{{ question }}",
        "{{ gate_type }}",
        "{{ recommendation_json }}",
        "{{ risks_html }}",
        "{{ evidence_html }}",
    ],
    "tests/test_approval_gate.py": [
        "test_valid_q_selection_proposal_passes",
        "test_invalid_gate_type_fails",
        "test_valid_decision_passes",
        "test_report_requires_decision_reference",
        "test_render_review_html_contains_question",
    ],
    "runtime/requirements-core.txt": ["numpy", "scipy", "scikit-image", "matplotlib", "openpyxl"],
    "runtime/requirements-nanonis.txt": ["nanonispy"],
    "runtime/requirements-ibw.txt": ["igorwriter"],
    "runtime/requirements-ai.txt": ["AI4STM"],
    "tests/test_runtime_defaults.py": [
        "test_default_probe_modules_exclude_legacy_ui_and_ai_detector",
        "test_default_probe_json_does_not_report_legacy_ui_or_ai_as_missing",
        "test_bootstrap_headless_and_all_groups_do_not_include_ui_or_ai",
        "test_resolver_bootstrap_command_ignores_pysidam_host_by_default",
    ],
    "runtime/constraints.txt": ["# Constraints"],
}

FORBIDDEN_TOKENS = [
    "Project FeSe",
    "map011",
    "20250926",
    "pxp_exports",
    "fe_site_analysis",
    "/Users/",
    "root__",
]

PUBLIC_BACKEND_FORBIDDEN_TOKENS = [
    "PYSIDAM_ROOT",
    "pysidam.",
    "PyQt5",
    "pyqtgraph",
    "QApplication",
    "/Users/",
    "Project FeSe",
    "pysidam-origin-main",
]

INCOMPLETE_MARKERS = ["T" + "BD", "TO" + "DO", "FIX" + "ME", "REPLACE" + "_ME"]


def read_text(rel_path: str) -> str:
    return (ROOT / rel_path).read_text(encoding="utf-8")


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    raise SystemExit(1)


def check_required_files() -> None:
    missing = [rel for rel in REQUIRED_FILES if not (ROOT / rel).is_file()]
    if missing:
        fail("missing required files: " + ", ".join(missing))


def check_required_tokens() -> None:
    for rel, tokens in REQUIRED_TOKENS.items():
        text = read_text(rel)
        missing = [token for token in tokens if token not in text]
        if missing:
            fail(f"{rel} is missing required text: {', '.join(missing)}")


def check_forbidden_tokens() -> None:
    checked_files = (
        list(ROOT.glob("*.md"))
        + list((ROOT / "references").rglob("*.md"))
        + list((ROOT / "references").rglob("*.json"))
    )
    for path in checked_files:
        text = path.read_text(encoding="utf-8")
        bad = [token for token in FORBIDDEN_TOKENS if token in text]
        if bad:
            fail(f"{path.relative_to(ROOT)} contains forbidden experiment-specific text: {', '.join(bad)}")
        incomplete = [marker for marker in INCOMPLETE_MARKERS if marker in text]
        if incomplete:
            fail(f"{path.relative_to(ROOT)} contains incomplete marker text: {', '.join(incomplete)}")


def check_skill_size() -> None:
    lines = read_text("SKILL.md").splitlines()
    if len(lines) > 180:
        fail(f"SKILL.md should stay thin; found {len(lines)} lines")


def check_portable_references() -> None:
    for path in (ROOT / "references").glob("*.md"):
        text = path.read_text(encoding="utf-8")
        if "REQUIRED SUB-SKILL" in text or "::git-" in text:
            fail(f"{path.relative_to(ROOT)} contains Codex-specific control syntax")


def check_fit_bridge_uses_pysidam_fitter() -> None:
    path = ROOT / "scripts" / "pysidam_agent" / "fit_gap.py"
    if not path.is_file():
        fail("missing fit bridge: scripts/pysidam_agent/fit_gap.py")
    text = path.read_text(encoding="utf-8")
    if "pysidam_agent_core.gap_fitting" not in text or "fit_gap_model_guarded" not in text:
        fail("fit_gap.py must call pysidam_agent_core.gap_fitting.fit_gap_model_guarded")
    forbidden = [
        "from scipy.optimize import least_squares",
        "from scipy.optimize import curve_fit",
        "scipy.optimize.least_squares",
        "scipy.optimize.curve_fit",
    ]
    bad = [token for token in forbidden if token in text]
    if bad:
        fail("fit_gap.py must keep optimization inside pysidam_agent_core: " + ", ".join(bad))


def check_headless_core_boundary() -> None:
    checked_files = list((ROOT / "pysidam_agent_core").glob("*.py"))
    checked_files.append(ROOT / "scripts" / "pysidam_agent" / "fit_gap.py")
    forbidden = [
        "PyQt5",
        "pyqtgraph",
        "QApplication",
        "QWidget",
        "pysidam.useful_tools.usefultools_deconvolution_point",
    ]
    for path in checked_files:
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        bad = [token for token in forbidden if token in text]
        if bad:
            fail(f"{path.relative_to(ROOT)} imports UI-bound fitting code: {', '.join(bad)}")


def check_public_backend_boundary() -> None:
    package_root = ROOT / "src" / "analystm"
    if not package_root.is_dir():
        fail("missing public backend package root: src/analystm")
    for path in package_root.rglob("*.py"):
        text = path.read_text(encoding="utf-8")
        bad = [token for token in PUBLIC_BACKEND_FORBIDDEN_TOKENS if token in text]
        if bad:
            fail(f"{path.relative_to(ROOT)} contains forbidden public-backend token(s): {', '.join(bad)}")


def main() -> int:
    check_required_files()
    check_required_tokens()
    check_forbidden_tokens()
    check_skill_size()
    check_portable_references()
    check_fit_bridge_uses_pysidam_fitter()
    check_headless_core_boundary()
    check_public_backend_boundary()
    print("PASS: stm-sjtm-data-processing package is structurally valid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())